services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=host.docker.internal
      - DB_NAME=
      - DB_USER=
      - DB_PASSWORD=
      - DB_PORT=
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always